// Copyright (c) OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: vault/dr_replication_service.proto

package vault

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DRReplication_StreamChanges_FullMethodName         = "/vault.DRReplication/StreamChanges"
	DRReplication_RequestCheckpoint_FullMethodName     = "/vault.DRReplication/RequestCheckpoint"
	DRReplication_ExchangeIBLT_FullMethodName          = "/vault.DRReplication/ExchangeIBLT"
	DRReplication_ExchangeRangeDigests_FullMethodName  = "/vault.DRReplication/ExchangeRangeDigests"
	DRReplication_ExchangePrefixDigests_FullMethodName = "/vault.DRReplication/ExchangePrefixDigests"
	DRReplication_FetchEntries_FullMethodName          = "/vault.DRReplication/FetchEntries"
	DRReplication_Heartbeat_FullMethodName             = "/vault.DRReplication/Heartbeat"
	DRReplication_SyncKeyring_FullMethodName           = "/vault.DRReplication/SyncKeyring"
)

// DRReplicationClient is the client API for DRReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DRReplication provides the cross-cluster gRPC service for disaster
// recovery replication. It supports two modes:
//
// Normal mode: Primary streams storage mutations to secondary via
// StreamChanges (entry-level change stream, not WAL shipping).
//
// Recovery mode: When the stream is interrupted or the secondary
// detects divergence, IBLT/prefix digest reconciliation identifies
// and repairs differences with bandwidth proportional to the number
// of differences (d), not the total keyspace (n).
type DRReplicationClient interface {
	// StreamChanges is the normal-mode replication stream. The primary
	// pushes storage mutations to the secondary in real time.
	StreamChanges(ctx context.Context, in *StreamChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntryChange], error)
	// RequestCheckpoint asks the primary to create a consistent
	// checkpoint at its current commit index for reconciliation.
	RequestCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	// ExchangeIBLT exchanges IBLT sketches to decode the actual
	// differing elements.
	ExchangeIBLT(ctx context.Context, in *IBLTMessage, opts ...grpc.CallOption) (*IBLTMessage, error)
	// ExchangeRangeDigests returns range digests for explicit spans from
	// an immutable checkpoint artifact. Used by secondaries to avoid blind
	// split fanout after decode failures.
	ExchangeRangeDigests(ctx context.Context, in *RangeDigestRequest, opts ...grpc.CallOption) (*RangeDigestResponse, error)
	// ExchangePrefixDigests exchanges prefix digest buckets for
	// adaptive drill-down when IBLT decode fails.
	ExchangePrefixDigests(ctx context.Context, in *PrefixDigestRequest, opts ...grpc.CallOption) (*PrefixDigestResponse, error)
	// FetchEntries retrieves the actual storage entries for a set of
	// divergent keys identified during reconciliation.
	FetchEntries(ctx context.Context, in *FetchEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntryBatch], error)
	// Heartbeat is a lightweight health check exchanging replication
	// state between primary and secondary.
	Heartbeat(ctx context.Context, in *DRHeartbeatRequest, opts ...grpc.CallOption) (*DRHeartbeatResponse, error)
	// SyncKeyring transfers the encrypted keyring blob from primary to
	// secondary during bootstrap. The secondary must share the same
	// seal configuration to decrypt it.
	SyncKeyring(ctx context.Context, in *SyncKeyringRequest, opts ...grpc.CallOption) (*SyncKeyringResponse, error)
}

type dRReplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewDRReplicationClient(cc grpc.ClientConnInterface) DRReplicationClient {
	return &dRReplicationClient{cc}
}

func (c *dRReplicationClient) StreamChanges(ctx context.Context, in *StreamChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntryChange], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DRReplication_ServiceDesc.Streams[0], DRReplication_StreamChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChangesRequest, EntryChange]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DRReplication_StreamChangesClient = grpc.ServerStreamingClient[EntryChange]

func (c *dRReplicationClient) RequestCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, DRReplication_RequestCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRReplicationClient) ExchangeIBLT(ctx context.Context, in *IBLTMessage, opts ...grpc.CallOption) (*IBLTMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IBLTMessage)
	err := c.cc.Invoke(ctx, DRReplication_ExchangeIBLT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRReplicationClient) ExchangeRangeDigests(ctx context.Context, in *RangeDigestRequest, opts ...grpc.CallOption) (*RangeDigestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeDigestResponse)
	err := c.cc.Invoke(ctx, DRReplication_ExchangeRangeDigests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRReplicationClient) ExchangePrefixDigests(ctx context.Context, in *PrefixDigestRequest, opts ...grpc.CallOption) (*PrefixDigestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefixDigestResponse)
	err := c.cc.Invoke(ctx, DRReplication_ExchangePrefixDigests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRReplicationClient) FetchEntries(ctx context.Context, in *FetchEntriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EntryBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DRReplication_ServiceDesc.Streams[1], DRReplication_FetchEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchEntriesRequest, EntryBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DRReplication_FetchEntriesClient = grpc.ServerStreamingClient[EntryBatch]

func (c *dRReplicationClient) Heartbeat(ctx context.Context, in *DRHeartbeatRequest, opts ...grpc.CallOption) (*DRHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DRHeartbeatResponse)
	err := c.cc.Invoke(ctx, DRReplication_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dRReplicationClient) SyncKeyring(ctx context.Context, in *SyncKeyringRequest, opts ...grpc.CallOption) (*SyncKeyringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncKeyringResponse)
	err := c.cc.Invoke(ctx, DRReplication_SyncKeyring_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DRReplicationServer is the server API for DRReplication service.
// All implementations must embed UnimplementedDRReplicationServer
// for forward compatibility.
//
// DRReplication provides the cross-cluster gRPC service for disaster
// recovery replication. It supports two modes:
//
// Normal mode: Primary streams storage mutations to secondary via
// StreamChanges (entry-level change stream, not WAL shipping).
//
// Recovery mode: When the stream is interrupted or the secondary
// detects divergence, IBLT/prefix digest reconciliation identifies
// and repairs differences with bandwidth proportional to the number
// of differences (d), not the total keyspace (n).
type DRReplicationServer interface {
	// StreamChanges is the normal-mode replication stream. The primary
	// pushes storage mutations to the secondary in real time.
	StreamChanges(*StreamChangesRequest, grpc.ServerStreamingServer[EntryChange]) error
	// RequestCheckpoint asks the primary to create a consistent
	// checkpoint at its current commit index for reconciliation.
	RequestCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	// ExchangeIBLT exchanges IBLT sketches to decode the actual
	// differing elements.
	ExchangeIBLT(context.Context, *IBLTMessage) (*IBLTMessage, error)
	// ExchangeRangeDigests returns range digests for explicit spans from
	// an immutable checkpoint artifact. Used by secondaries to avoid blind
	// split fanout after decode failures.
	ExchangeRangeDigests(context.Context, *RangeDigestRequest) (*RangeDigestResponse, error)
	// ExchangePrefixDigests exchanges prefix digest buckets for
	// adaptive drill-down when IBLT decode fails.
	ExchangePrefixDigests(context.Context, *PrefixDigestRequest) (*PrefixDigestResponse, error)
	// FetchEntries retrieves the actual storage entries for a set of
	// divergent keys identified during reconciliation.
	FetchEntries(*FetchEntriesRequest, grpc.ServerStreamingServer[EntryBatch]) error
	// Heartbeat is a lightweight health check exchanging replication
	// state between primary and secondary.
	Heartbeat(context.Context, *DRHeartbeatRequest) (*DRHeartbeatResponse, error)
	// SyncKeyring transfers the encrypted keyring blob from primary to
	// secondary during bootstrap. The secondary must share the same
	// seal configuration to decrypt it.
	SyncKeyring(context.Context, *SyncKeyringRequest) (*SyncKeyringResponse, error)
	mustEmbedUnimplementedDRReplicationServer()
}

// UnimplementedDRReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDRReplicationServer struct{}

func (UnimplementedDRReplicationServer) StreamChanges(*StreamChangesRequest, grpc.ServerStreamingServer[EntryChange]) error {
	return status.Error(codes.Unimplemented, "method StreamChanges not implemented")
}
func (UnimplementedDRReplicationServer) RequestCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCheckpoint not implemented")
}
func (UnimplementedDRReplicationServer) ExchangeIBLT(context.Context, *IBLTMessage) (*IBLTMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeIBLT not implemented")
}
func (UnimplementedDRReplicationServer) ExchangeRangeDigests(context.Context, *RangeDigestRequest) (*RangeDigestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeRangeDigests not implemented")
}
func (UnimplementedDRReplicationServer) ExchangePrefixDigests(context.Context, *PrefixDigestRequest) (*PrefixDigestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangePrefixDigests not implemented")
}
func (UnimplementedDRReplicationServer) FetchEntries(*FetchEntriesRequest, grpc.ServerStreamingServer[EntryBatch]) error {
	return status.Error(codes.Unimplemented, "method FetchEntries not implemented")
}
func (UnimplementedDRReplicationServer) Heartbeat(context.Context, *DRHeartbeatRequest) (*DRHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDRReplicationServer) SyncKeyring(context.Context, *SyncKeyringRequest) (*SyncKeyringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncKeyring not implemented")
}
func (UnimplementedDRReplicationServer) mustEmbedUnimplementedDRReplicationServer() {}
func (UnimplementedDRReplicationServer) testEmbeddedByValue()                       {}

// UnsafeDRReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DRReplicationServer will
// result in compilation errors.
type UnsafeDRReplicationServer interface {
	mustEmbedUnimplementedDRReplicationServer()
}

func RegisterDRReplicationServer(s grpc.ServiceRegistrar, srv DRReplicationServer) {
	// If the following call panics, it indicates UnimplementedDRReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DRReplication_ServiceDesc, srv)
}

func _DRReplication_StreamChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DRReplicationServer).StreamChanges(m, &grpc.GenericServerStream[StreamChangesRequest, EntryChange]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DRReplication_StreamChangesServer = grpc.ServerStreamingServer[EntryChange]

func _DRReplication_RequestCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRReplicationServer).RequestCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DRReplication_RequestCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRReplicationServer).RequestCheckpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DRReplication_ExchangeIBLT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IBLTMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRReplicationServer).ExchangeIBLT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DRReplication_ExchangeIBLT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRReplicationServer).ExchangeIBLT(ctx, req.(*IBLTMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _DRReplication_ExchangeRangeDigests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeDigestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRReplicationServer).ExchangeRangeDigests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DRReplication_ExchangeRangeDigests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRReplicationServer).ExchangeRangeDigests(ctx, req.(*RangeDigestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DRReplication_ExchangePrefixDigests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrefixDigestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRReplicationServer).ExchangePrefixDigests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DRReplication_ExchangePrefixDigests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRReplicationServer).ExchangePrefixDigests(ctx, req.(*PrefixDigestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DRReplication_FetchEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchEntriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DRReplicationServer).FetchEntries(m, &grpc.GenericServerStream[FetchEntriesRequest, EntryBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DRReplication_FetchEntriesServer = grpc.ServerStreamingServer[EntryBatch]

func _DRReplication_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DRHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRReplicationServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DRReplication_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRReplicationServer).Heartbeat(ctx, req.(*DRHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DRReplication_SyncKeyring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncKeyringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DRReplicationServer).SyncKeyring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DRReplication_SyncKeyring_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DRReplicationServer).SyncKeyring(ctx, req.(*SyncKeyringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DRReplication_ServiceDesc is the grpc.ServiceDesc for DRReplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DRReplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault.DRReplication",
	HandlerType: (*DRReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCheckpoint",
			Handler:    _DRReplication_RequestCheckpoint_Handler,
		},
		{
			MethodName: "ExchangeIBLT",
			Handler:    _DRReplication_ExchangeIBLT_Handler,
		},
		{
			MethodName: "ExchangeRangeDigests",
			Handler:    _DRReplication_ExchangeRangeDigests_Handler,
		},
		{
			MethodName: "ExchangePrefixDigests",
			Handler:    _DRReplication_ExchangePrefixDigests_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DRReplication_Heartbeat_Handler,
		},
		{
			MethodName: "SyncKeyring",
			Handler:    _DRReplication_SyncKeyring_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChanges",
			Handler:       _DRReplication_StreamChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchEntries",
			Handler:       _DRReplication_FetchEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vault/dr_replication_service.proto",
}
