// Copyright (c) OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: vault/dr_replication_service.proto

package vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryChange represents a single storage mutation.
type EntryChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// op_type: "put" or "delete"
	OpType string `protobuf:"bytes,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	// key is the storage path.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// value is the (encrypted) entry bytes. Empty for deletes.
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// seal_wrap indicates if the entry uses seal wrapping.
	SealWrap bool `protobuf:"varint,4,opt,name=seal_wrap,json=sealWrap,proto3" json:"seal_wrap,omitempty"`
	// raft_index is the primary's Raft log index for this mutation.
	RaftIndex uint64 `protobuf:"varint,5,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	// kid is the Key IDentifier (HMAC of the storage key). Used in
	// FetchEntries delete responses where the primary cannot resolve
	// the key (it was deleted). The secondary uses its local KID->key
	// map to resolve the actual storage path.
	Kid           []byte `protobuf:"bytes,6,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryChange) Reset() {
	*x = EntryChange{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryChange) ProtoMessage() {}

func (x *EntryChange) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryChange.ProtoReflect.Descriptor instead.
func (*EntryChange) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{0}
}

func (x *EntryChange) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *EntryChange) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EntryChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EntryChange) GetSealWrap() bool {
	if x != nil {
		return x.SealWrap
	}
	return false
}

func (x *EntryChange) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

func (x *EntryChange) GetKid() []byte {
	if x != nil {
		return x.Kid
	}
	return nil
}

// StreamChangesRequest initiates the change stream from primary.
type StreamChangesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relationship_id identifies the DR relationship.
	RelationshipId string `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	// last_applied_index is the secondary's last known primary index.
	// Used as a hint for the primary to skip already-applied entries.
	LastAppliedIndex uint64 `protobuf:"varint,2,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamChangesRequest) Reset() {
	*x = StreamChangesRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChangesRequest) ProtoMessage() {}

func (x *StreamChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamChangesRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{1}
}

func (x *StreamChangesRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *StreamChangesRequest) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

// CheckpointRequest asks the primary to create a reconciliation checkpoint.
type CheckpointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckpointRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

// CheckpointResponse contains the checkpoint details.
type CheckpointResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// checkpoint_id is a unique identifier for this checkpoint.
	CheckpointId string `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// commit_index is the primary's Raft commit index at checkpoint time.
	CommitIndex uint64 `protobuf:"varint,2,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	// top_ranges is the primary-generated deterministic top-level range
	// manifest for range-based reconciliation.
	TopRanges []*RangeDigest `protobuf:"bytes,3,rep,name=top_ranges,json=topRanges,proto3" json:"top_ranges,omitempty"`
	// range_plan_version identifies the deterministic range planner
	// algorithm used to generate top_ranges.
	RangePlanVersion uint32 `protobuf:"varint,4,opt,name=range_plan_version,json=rangePlanVersion,proto3" json:"range_plan_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckpointResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CheckpointResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *CheckpointResponse) GetTopRanges() []*RangeDigest {
	if x != nil {
		return x.TopRanges
	}
	return nil
}

func (x *CheckpointResponse) GetRangePlanVersion() uint32 {
	if x != nil {
		return x.RangePlanVersion
	}
	return 0
}

// RangeSpan is an inclusive KID interval.
type RangeSpan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start_kid and end_kid are inclusive 32-byte KID boundaries.
	StartKid []byte `protobuf:"bytes,1,opt,name=start_kid,json=startKid,proto3" json:"start_kid,omitempty"`
	EndKid   []byte `protobuf:"bytes,2,opt,name=end_kid,json=endKid,proto3" json:"end_kid,omitempty"`
	// split_depth indicates adaptive split depth from the parent range.
	SplitDepth    uint32 `protobuf:"varint,3,opt,name=split_depth,json=splitDepth,proto3" json:"split_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeSpan) Reset() {
	*x = RangeSpan{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSpan) ProtoMessage() {}

func (x *RangeSpan) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSpan.ProtoReflect.Descriptor instead.
func (*RangeSpan) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{4}
}

func (x *RangeSpan) GetStartKid() []byte {
	if x != nil {
		return x.StartKid
	}
	return nil
}

func (x *RangeSpan) GetEndKid() []byte {
	if x != nil {
		return x.EndKid
	}
	return nil
}

func (x *RangeSpan) GetSplitDepth() uint32 {
	if x != nil {
		return x.SplitDepth
	}
	return 0
}

// RangeDigest summarizes a KID interval for mismatch detection and sizing hints.
type RangeDigest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Span               *RangeSpan             `protobuf:"bytes,1,opt,name=span,proto3" json:"span,omitempty"`
	Count              uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XorKeyHash         []byte                 `protobuf:"bytes,3,opt,name=xor_key_hash,json=xorKeyHash,proto3" json:"xor_key_hash,omitempty"`
	XorValueHash       []byte                 `protobuf:"bytes,4,opt,name=xor_value_hash,json=xorValueHash,proto3" json:"xor_value_hash,omitempty"`
	SuggestedIbltCells uint32                 `protobuf:"varint,5,opt,name=suggested_iblt_cells,json=suggestedIbltCells,proto3" json:"suggested_iblt_cells,omitempty"`
	ApproxValueBytes   uint64                 `protobuf:"varint,6,opt,name=approx_value_bytes,json=approxValueBytes,proto3" json:"approx_value_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RangeDigest) Reset() {
	*x = RangeDigest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDigest) ProtoMessage() {}

func (x *RangeDigest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDigest.ProtoReflect.Descriptor instead.
func (*RangeDigest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{5}
}

func (x *RangeDigest) GetSpan() *RangeSpan {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *RangeDigest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RangeDigest) GetXorKeyHash() []byte {
	if x != nil {
		return x.XorKeyHash
	}
	return nil
}

func (x *RangeDigest) GetXorValueHash() []byte {
	if x != nil {
		return x.XorValueHash
	}
	return nil
}

func (x *RangeDigest) GetSuggestedIbltCells() uint32 {
	if x != nil {
		return x.SuggestedIbltCells
	}
	return 0
}

func (x *RangeDigest) GetApproxValueBytes() uint64 {
	if x != nil {
		return x.ApproxValueBytes
	}
	return 0
}

// RangeDigestRequest asks the primary for digest metadata of explicit spans.
type RangeDigestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId    string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	CheckpointIndex uint64                 `protobuf:"varint,2,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	Spans           []*RangeSpan           `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RangeDigestRequest) Reset() {
	*x = RangeDigestRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDigestRequest) ProtoMessage() {}

func (x *RangeDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDigestRequest.ProtoReflect.Descriptor instead.
func (*RangeDigestRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{6}
}

func (x *RangeDigestRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *RangeDigestRequest) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *RangeDigestRequest) GetSpans() []*RangeSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

// RangeDigestResponse returns one digest per requested span.
type RangeDigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranges        []*RangeDigest         `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeDigestResponse) Reset() {
	*x = RangeDigestResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDigestResponse) ProtoMessage() {}

func (x *RangeDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDigestResponse.ProtoReflect.Descriptor instead.
func (*RangeDigestResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{7}
}

func (x *RangeDigestResponse) GetRanges() []*RangeDigest {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// IBLTMessage carries a serialized IBLT.
type IBLTMessage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// num_cells is the IBLT size (for informational purposes).
	NumCells uint32 `protobuf:"varint,2,opt,name=num_cells,json=numCells,proto3" json:"num_cells,omitempty"`
	// iblt_data is the serialized IBLT.
	IbltData []byte `protobuf:"bytes,3,opt,name=iblt_data,json=ibltData,proto3" json:"iblt_data,omitempty"`
	// span optionally scopes IBLT exchange to a specific KID interval.
	// When unset, global behavior is used.
	Span *RangeSpan `protobuf:"bytes,4,opt,name=span,proto3" json:"span,omitempty"`
	// checkpoint_index fences this request to a specific checkpoint tuple.
	CheckpointIndex uint64 `protobuf:"varint,5,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IBLTMessage) Reset() {
	*x = IBLTMessage{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IBLTMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBLTMessage) ProtoMessage() {}

func (x *IBLTMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBLTMessage.ProtoReflect.Descriptor instead.
func (*IBLTMessage) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{8}
}

func (x *IBLTMessage) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *IBLTMessage) GetNumCells() uint32 {
	if x != nil {
		return x.NumCells
	}
	return 0
}

func (x *IBLTMessage) GetIbltData() []byte {
	if x != nil {
		return x.IbltData
	}
	return nil
}

func (x *IBLTMessage) GetSpan() *RangeSpan {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *IBLTMessage) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

// PrefixDigestRequest requests prefix digests at a given depth.
type PrefixDigestRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// prefix_length is the number of prefix bits (e.g. 8, 12, 16).
	PrefixLength uint32 `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	// bucket_indices restricts the response to specific buckets.
	// Empty means all buckets at this prefix length.
	BucketIndices []uint32 `protobuf:"varint,3,rep,packed,name=bucket_indices,json=bucketIndices,proto3" json:"bucket_indices,omitempty"`
	// span optionally scopes digest generation to a specific KID interval.
	// When unset, global behavior is used.
	Span *RangeSpan `protobuf:"bytes,4,opt,name=span,proto3" json:"span,omitempty"`
	// checkpoint_index fences this request to a specific checkpoint tuple.
	CheckpointIndex uint64 `protobuf:"varint,5,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrefixDigestRequest) Reset() {
	*x = PrefixDigestRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixDigestRequest) ProtoMessage() {}

func (x *PrefixDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixDigestRequest.ProtoReflect.Descriptor instead.
func (*PrefixDigestRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{9}
}

func (x *PrefixDigestRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *PrefixDigestRequest) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *PrefixDigestRequest) GetBucketIndices() []uint32 {
	if x != nil {
		return x.BucketIndices
	}
	return nil
}

func (x *PrefixDigestRequest) GetSpan() *RangeSpan {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *PrefixDigestRequest) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

// PrefixDigestResponse returns prefix digest buckets.
type PrefixDigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixLength  uint32                 `protobuf:"varint,1,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	Buckets       []*BucketDigestProto   `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixDigestResponse) Reset() {
	*x = PrefixDigestResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixDigestResponse) ProtoMessage() {}

func (x *PrefixDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixDigestResponse.ProtoReflect.Descriptor instead.
func (*PrefixDigestResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{10}
}

func (x *PrefixDigestResponse) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *PrefixDigestResponse) GetBuckets() []*BucketDigestProto {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// BucketDigestProto is the wire representation of a single prefix bucket.
type BucketDigestProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XorKeyHash    []byte                 `protobuf:"bytes,3,opt,name=xor_key_hash,json=xorKeyHash,proto3" json:"xor_key_hash,omitempty"`
	XorValueHash  []byte                 `protobuf:"bytes,4,opt,name=xor_value_hash,json=xorValueHash,proto3" json:"xor_value_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketDigestProto) Reset() {
	*x = BucketDigestProto{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketDigestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDigestProto) ProtoMessage() {}

func (x *BucketDigestProto) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDigestProto.ProtoReflect.Descriptor instead.
func (*BucketDigestProto) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{11}
}

func (x *BucketDigestProto) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BucketDigestProto) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BucketDigestProto) GetXorKeyHash() []byte {
	if x != nil {
		return x.XorKeyHash
	}
	return nil
}

func (x *BucketDigestProto) GetXorValueHash() []byte {
	if x != nil {
		return x.XorValueHash
	}
	return nil
}

// FetchEntriesRequest asks the primary for specific entries by KID.
type FetchItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid identifies the item to fetch.
	Kid []byte `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// expected_vid is the VID derived on the secondary from the active
	// checkpoint diff. The primary must verify fetched value provenance.
	ExpectedVid   []byte `protobuf:"bytes,2,opt,name=expected_vid,json=expectedVid,proto3" json:"expected_vid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItem) Reset() {
	*x = FetchItem{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItem) ProtoMessage() {}

func (x *FetchItem) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItem.ProtoReflect.Descriptor instead.
func (*FetchItem) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{12}
}

func (x *FetchItem) GetKid() []byte {
	if x != nil {
		return x.Kid
	}
	return nil
}

func (x *FetchItem) GetExpectedVid() []byte {
	if x != nil {
		return x.ExpectedVid
	}
	return nil
}

// FetchEntriesRequest asks the primary for specific entries by KID.
type FetchEntriesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// kids is the list of KID hashes to fetch entries for.
	Kids [][]byte `protobuf:"bytes,2,rep,name=kids,proto3" json:"kids,omitempty"`
	// include_deletes indicates whether tombstoned/deleted entries
	// should be included in the response.
	IncludeDeletes bool `protobuf:"varint,3,opt,name=include_deletes,json=includeDeletes,proto3" json:"include_deletes,omitempty"`
	// bucket_prefix_length and bucket_indices enable bucket-based
	// fetching for prefix digest reconciliation. When set, the primary
	// returns all entries whose KID falls into the specified buckets,
	// not just the KIDs listed in the kids field.
	BucketPrefixLength uint32   `protobuf:"varint,4,opt,name=bucket_prefix_length,json=bucketPrefixLength,proto3" json:"bucket_prefix_length,omitempty"`
	BucketIndices      []uint32 `protobuf:"varint,5,rep,packed,name=bucket_indices,json=bucketIndices,proto3" json:"bucket_indices,omitempty"`
	// ranges optionally requests all entries in the provided KID intervals.
	Ranges []*RangeSpan `protobuf:"bytes,6,rep,name=ranges,proto3" json:"ranges,omitempty"`
	// checkpoint_index fences this request to a specific checkpoint tuple.
	CheckpointIndex uint64 `protobuf:"varint,7,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	// items is a provenance-safe fetch list of (KID, expected_VID) pairs.
	// When checkpoint_index is set and point fetches are requested, items
	// should be used instead of kids.
	Items         []*FetchItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchEntriesRequest) Reset() {
	*x = FetchEntriesRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEntriesRequest) ProtoMessage() {}

func (x *FetchEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEntriesRequest.ProtoReflect.Descriptor instead.
func (*FetchEntriesRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{13}
}

func (x *FetchEntriesRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *FetchEntriesRequest) GetKids() [][]byte {
	if x != nil {
		return x.Kids
	}
	return nil
}

func (x *FetchEntriesRequest) GetIncludeDeletes() bool {
	if x != nil {
		return x.IncludeDeletes
	}
	return false
}

func (x *FetchEntriesRequest) GetBucketPrefixLength() uint32 {
	if x != nil {
		return x.BucketPrefixLength
	}
	return 0
}

func (x *FetchEntriesRequest) GetBucketIndices() []uint32 {
	if x != nil {
		return x.BucketIndices
	}
	return nil
}

func (x *FetchEntriesRequest) GetRanges() []*RangeSpan {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *FetchEntriesRequest) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *FetchEntriesRequest) GetItems() []*FetchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// EntryBatch is a batch of storage entries.
type EntryBatch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*EntryChange         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// errors lists KIDs that could not be fetched due to storage
	// errors. The secondary should retry these in a subsequent
	// reconciliation pass.
	FailedKids [][]byte `protobuf:"bytes,2,rep,name=failed_kids,json=failedKids,proto3" json:"failed_kids,omitempty"`
	// checkpoint tuple provenance for this batch.
	CheckpointId    string `protobuf:"bytes,3,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	CheckpointIndex uint64 `protobuf:"varint,4,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EntryBatch) Reset() {
	*x = EntryBatch{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryBatch) ProtoMessage() {}

func (x *EntryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryBatch.ProtoReflect.Descriptor instead.
func (*EntryBatch) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{14}
}

func (x *EntryBatch) GetEntries() []*EntryChange {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *EntryBatch) GetFailedKids() [][]byte {
	if x != nil {
		return x.FailedKids
	}
	return nil
}

func (x *EntryBatch) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *EntryBatch) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

// DRHeartbeatRequest is sent periodically from secondary to primary.
type DRHeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	AppliedIndex   uint64                 `protobuf:"varint,2,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	Term           uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	NodeId         string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DRHeartbeatRequest) Reset() {
	*x = DRHeartbeatRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRHeartbeatRequest) ProtoMessage() {}

func (x *DRHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*DRHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{15}
}

func (x *DRHeartbeatRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *DRHeartbeatRequest) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *DRHeartbeatRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *DRHeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// DRHeartbeatResponse is the primary's reply to a heartbeat.
type DRHeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrimaryIndex     uint64                 `protobuf:"varint,1,opt,name=primary_index,json=primaryIndex,proto3" json:"primary_index,omitempty"`
	PrimaryTerm      uint64                 `protobuf:"varint,2,opt,name=primary_term,json=primaryTerm,proto3" json:"primary_term,omitempty"`
	ReplicationState uint32                 `protobuf:"varint,3,opt,name=replication_state,json=replicationState,proto3" json:"replication_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DRHeartbeatResponse) Reset() {
	*x = DRHeartbeatResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRHeartbeatResponse) ProtoMessage() {}

func (x *DRHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*DRHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{16}
}

func (x *DRHeartbeatResponse) GetPrimaryIndex() uint64 {
	if x != nil {
		return x.PrimaryIndex
	}
	return 0
}

func (x *DRHeartbeatResponse) GetPrimaryTerm() uint64 {
	if x != nil {
		return x.PrimaryTerm
	}
	return 0
}

func (x *DRHeartbeatResponse) GetReplicationState() uint32 {
	if x != nil {
		return x.ReplicationState
	}
	return 0
}

// SyncKeyringRequest is sent by the secondary during bootstrap to
// request the primary's keyring.
type SyncKeyringRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId        string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	ClientEphemeralPubkey []byte                 `protobuf:"bytes,2,opt,name=client_ephemeral_pubkey,json=clientEphemeralPubkey,proto3" json:"client_ephemeral_pubkey,omitempty"`
	ClientNonce           []byte                 `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncKeyringRequest) Reset() {
	*x = SyncKeyringRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeyringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeyringRequest) ProtoMessage() {}

func (x *SyncKeyringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeyringRequest.ProtoReflect.Descriptor instead.
func (*SyncKeyringRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{17}
}

func (x *SyncKeyringRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *SyncKeyringRequest) GetClientEphemeralPubkey() []byte {
	if x != nil {
		return x.ClientEphemeralPubkey
	}
	return nil
}

func (x *SyncKeyringRequest) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

// SyncKeyringResponse carries the encrypted keyring, root key entry,
// and the root key wrapped to the secondary's ephemeral public key.
type SyncKeyringResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keyring_entry is the raw value of "core/keyring" from physical storage.
	KeyringEntry []byte `protobuf:"bytes,1,opt,name=keyring_entry,json=keyringEntry,proto3" json:"keyring_entry,omitempty"`
	// root_key_entry is the raw value of "core/root-key" from physical storage.
	RootKeyEntry []byte `protobuf:"bytes,2,opt,name=root_key_entry,json=rootKeyEntry,proto3" json:"root_key_entry,omitempty"`
	// wrapped_root_key is the root key encrypted with a symmetric key
	// derived from ECDH(primary_ephemeral, secondary_ephemeral_pubkey).
	WrappedRootKey []byte `protobuf:"bytes,3,opt,name=wrapped_root_key,json=wrappedRootKey,proto3" json:"wrapped_root_key,omitempty"`
	// server_ephemeral_pubkey is the primary's ephemeral public key used
	// for ECDH key agreement.
	ServerEphemeralPubkey []byte `protobuf:"bytes,4,opt,name=server_ephemeral_pubkey,json=serverEphemeralPubkey,proto3" json:"server_ephemeral_pubkey,omitempty"`
	// wrap_nonce is the AEAD nonce used to encrypt wrapped_root_key.
	WrapNonce []byte `protobuf:"bytes,5,opt,name=wrap_nonce,json=wrapNonce,proto3" json:"wrap_nonce,omitempty"`
	// wrap_aad_version is the protocol version encoded in AEAD AAD.
	WrapAadVersion uint32 `protobuf:"varint,6,opt,name=wrap_aad_version,json=wrapAadVersion,proto3" json:"wrap_aad_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncKeyringResponse) Reset() {
	*x = SyncKeyringResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeyringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeyringResponse) ProtoMessage() {}

func (x *SyncKeyringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeyringResponse.ProtoReflect.Descriptor instead.
func (*SyncKeyringResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{18}
}

func (x *SyncKeyringResponse) GetKeyringEntry() []byte {
	if x != nil {
		return x.KeyringEntry
	}
	return nil
}

func (x *SyncKeyringResponse) GetRootKeyEntry() []byte {
	if x != nil {
		return x.RootKeyEntry
	}
	return nil
}

func (x *SyncKeyringResponse) GetWrappedRootKey() []byte {
	if x != nil {
		return x.WrappedRootKey
	}
	return nil
}

func (x *SyncKeyringResponse) GetServerEphemeralPubkey() []byte {
	if x != nil {
		return x.ServerEphemeralPubkey
	}
	return nil
}

func (x *SyncKeyringResponse) GetWrapNonce() []byte {
	if x != nil {
		return x.WrapNonce
	}
	return nil
}

func (x *SyncKeyringResponse) GetWrapAadVersion() uint32 {
	if x != nil {
		return x.WrapAadVersion
	}
	return 0
}

var File_vault_dr_replication_service_proto protoreflect.FileDescriptor

const file_vault_dr_replication_service_proto_rawDesc = "" +
	"\n" +
	"\"vault/dr_replication_service.proto\x12\x05vault\"\x9c\x01\n" +
	"\vEntryChange\x12\x17\n" +
	"\aop_type\x18\x01 \x01(\tR\x06opType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\tseal_wrap\x18\x04 \x01(\bR\bsealWrap\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x05 \x01(\x04R\traftIndex\x12\x10\n" +
	"\x03kid\x18\x06 \x01(\fR\x03kid\"m\n" +
	"\x14StreamChangesRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x12,\n" +
	"\x12last_applied_index\x18\x02 \x01(\x04R\x10lastAppliedIndex\"<\n" +
	"\x11CheckpointRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\"\xbd\x01\n" +
	"\x12CheckpointResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12!\n" +
	"\fcommit_index\x18\x02 \x01(\x04R\vcommitIndex\x121\n" +
	"\n" +
	"top_ranges\x18\x03 \x03(\v2\x12.vault.RangeDigestR\ttopRanges\x12,\n" +
	"\x12range_plan_version\x18\x04 \x01(\rR\x10rangePlanVersion\"b\n" +
	"\tRangeSpan\x12\x1b\n" +
	"\tstart_kid\x18\x01 \x01(\fR\bstartKid\x12\x17\n" +
	"\aend_kid\x18\x02 \x01(\fR\x06endKid\x12\x1f\n" +
	"\vsplit_depth\x18\x03 \x01(\rR\n" +
	"splitDepth\"\xf1\x01\n" +
	"\vRangeDigest\x12$\n" +
	"\x04span\x18\x01 \x01(\v2\x10.vault.RangeSpanR\x04span\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12 \n" +
	"\fxor_key_hash\x18\x03 \x01(\fR\n" +
	"xorKeyHash\x12$\n" +
	"\x0exor_value_hash\x18\x04 \x01(\fR\fxorValueHash\x120\n" +
	"\x14suggested_iblt_cells\x18\x05 \x01(\rR\x12suggestedIbltCells\x12,\n" +
	"\x12approx_value_bytes\x18\x06 \x01(\x04R\x10approxValueBytes\"\x8c\x01\n" +
	"\x12RangeDigestRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12)\n" +
	"\x10checkpoint_index\x18\x02 \x01(\x04R\x0fcheckpointIndex\x12&\n" +
	"\x05spans\x18\x03 \x03(\v2\x10.vault.RangeSpanR\x05spans\"A\n" +
	"\x13RangeDigestResponse\x12*\n" +
	"\x06ranges\x18\x01 \x03(\v2\x12.vault.RangeDigestR\x06ranges\"\xbd\x01\n" +
	"\vIBLTMessage\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x1b\n" +
	"\tnum_cells\x18\x02 \x01(\rR\bnumCells\x12\x1b\n" +
	"\tiblt_data\x18\x03 \x01(\fR\bibltData\x12$\n" +
	"\x04span\x18\x04 \x01(\v2\x10.vault.RangeSpanR\x04span\x12)\n" +
	"\x10checkpoint_index\x18\x05 \x01(\x04R\x0fcheckpointIndex\"\xd7\x01\n" +
	"\x13PrefixDigestRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12#\n" +
	"\rprefix_length\x18\x02 \x01(\rR\fprefixLength\x12%\n" +
	"\x0ebucket_indices\x18\x03 \x03(\rR\rbucketIndices\x12$\n" +
	"\x04span\x18\x04 \x01(\v2\x10.vault.RangeSpanR\x04span\x12)\n" +
	"\x10checkpoint_index\x18\x05 \x01(\x04R\x0fcheckpointIndex\"o\n" +
	"\x14PrefixDigestResponse\x12#\n" +
	"\rprefix_length\x18\x01 \x01(\rR\fprefixLength\x122\n" +
	"\abuckets\x18\x02 \x03(\v2\x18.vault.BucketDigestProtoR\abuckets\"\x87\x01\n" +
	"\x11BucketDigestProto\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12 \n" +
	"\fxor_key_hash\x18\x03 \x01(\fR\n" +
	"xorKeyHash\x12$\n" +
	"\x0exor_value_hash\x18\x04 \x01(\fR\fxorValueHash\"@\n" +
	"\tFetchItem\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\fR\x03kid\x12!\n" +
	"\fexpected_vid\x18\x02 \x01(\fR\vexpectedVid\"\xcd\x02\n" +
	"\x13FetchEntriesRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x12\n" +
	"\x04kids\x18\x02 \x03(\fR\x04kids\x12'\n" +
	"\x0finclude_deletes\x18\x03 \x01(\bR\x0eincludeDeletes\x120\n" +
	"\x14bucket_prefix_length\x18\x04 \x01(\rR\x12bucketPrefixLength\x12%\n" +
	"\x0ebucket_indices\x18\x05 \x03(\rR\rbucketIndices\x12(\n" +
	"\x06ranges\x18\x06 \x03(\v2\x10.vault.RangeSpanR\x06ranges\x12)\n" +
	"\x10checkpoint_index\x18\a \x01(\x04R\x0fcheckpointIndex\x12&\n" +
	"\x05items\x18\b \x03(\v2\x10.vault.FetchItemR\x05items\"\xab\x01\n" +
	"\n" +
	"EntryBatch\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.vault.EntryChangeR\aentries\x12\x1f\n" +
	"\vfailed_kids\x18\x02 \x03(\fR\n" +
	"failedKids\x12#\n" +
	"\rcheckpoint_id\x18\x03 \x01(\tR\fcheckpointId\x12)\n" +
	"\x10checkpoint_index\x18\x04 \x01(\x04R\x0fcheckpointIndex\"\x8f\x01\n" +
	"\x12DRHeartbeatRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x12#\n" +
	"\rapplied_index\x18\x02 \x01(\x04R\fappliedIndex\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"\x8a\x01\n" +
	"\x13DRHeartbeatResponse\x12#\n" +
	"\rprimary_index\x18\x01 \x01(\x04R\fprimaryIndex\x12!\n" +
	"\fprimary_term\x18\x02 \x01(\x04R\vprimaryTerm\x12+\n" +
	"\x11replication_state\x18\x03 \x01(\rR\x10replicationState\"\x98\x01\n" +
	"\x12SyncKeyringRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x126\n" +
	"\x17client_ephemeral_pubkey\x18\x02 \x01(\fR\x15clientEphemeralPubkey\x12!\n" +
	"\fclient_nonce\x18\x03 \x01(\fR\vclientNonce\"\x8b\x02\n" +
	"\x13SyncKeyringResponse\x12#\n" +
	"\rkeyring_entry\x18\x01 \x01(\fR\fkeyringEntry\x12$\n" +
	"\x0eroot_key_entry\x18\x02 \x01(\fR\frootKeyEntry\x12(\n" +
	"\x10wrapped_root_key\x18\x03 \x01(\fR\x0ewrappedRootKey\x126\n" +
	"\x17server_ephemeral_pubkey\x18\x04 \x01(\fR\x15serverEphemeralPubkey\x12\x1d\n" +
	"\n" +
	"wrap_nonce\x18\x05 \x01(\fR\twrapNonce\x12(\n" +
	"\x10wrap_aad_version\x18\x06 \x01(\rR\x0ewrapAadVersion2\xd1\x04\n" +
	"\rDRReplication\x12D\n" +
	"\rStreamChanges\x12\x1b.vault.StreamChangesRequest\x1a\x12.vault.EntryChange\"\x000\x01\x12J\n" +
	"\x11RequestCheckpoint\x12\x18.vault.CheckpointRequest\x1a\x19.vault.CheckpointResponse\"\x00\x128\n" +
	"\fExchangeIBLT\x12\x12.vault.IBLTMessage\x1a\x12.vault.IBLTMessage\"\x00\x12O\n" +
	"\x14ExchangeRangeDigests\x12\x19.vault.RangeDigestRequest\x1a\x1a.vault.RangeDigestResponse\"\x00\x12R\n" +
	"\x15ExchangePrefixDigests\x12\x1a.vault.PrefixDigestRequest\x1a\x1b.vault.PrefixDigestResponse\"\x00\x12A\n" +
	"\fFetchEntries\x12\x1a.vault.FetchEntriesRequest\x1a\x11.vault.EntryBatch\"\x000\x01\x12D\n" +
	"\tHeartbeat\x12\x19.vault.DRHeartbeatRequest\x1a\x1a.vault.DRHeartbeatResponse\"\x00\x12F\n" +
	"\vSyncKeyring\x12\x19.vault.SyncKeyringRequest\x1a\x1a.vault.SyncKeyringResponse\"\x00B\"Z github.com/openbao/openbao/vaultb\x06proto3"

var (
	file_vault_dr_replication_service_proto_rawDescOnce sync.Once
	file_vault_dr_replication_service_proto_rawDescData []byte
)

func file_vault_dr_replication_service_proto_rawDescGZIP() []byte {
	file_vault_dr_replication_service_proto_rawDescOnce.Do(func() {
		file_vault_dr_replication_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_dr_replication_service_proto_rawDesc), len(file_vault_dr_replication_service_proto_rawDesc)))
	})
	return file_vault_dr_replication_service_proto_rawDescData
}

var file_vault_dr_replication_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_vault_dr_replication_service_proto_goTypes = []any{
	(*EntryChange)(nil),          // 0: vault.EntryChange
	(*StreamChangesRequest)(nil), // 1: vault.StreamChangesRequest
	(*CheckpointRequest)(nil),    // 2: vault.CheckpointRequest
	(*CheckpointResponse)(nil),   // 3: vault.CheckpointResponse
	(*RangeSpan)(nil),            // 4: vault.RangeSpan
	(*RangeDigest)(nil),          // 5: vault.RangeDigest
	(*RangeDigestRequest)(nil),   // 6: vault.RangeDigestRequest
	(*RangeDigestResponse)(nil),  // 7: vault.RangeDigestResponse
	(*IBLTMessage)(nil),          // 8: vault.IBLTMessage
	(*PrefixDigestRequest)(nil),  // 9: vault.PrefixDigestRequest
	(*PrefixDigestResponse)(nil), // 10: vault.PrefixDigestResponse
	(*BucketDigestProto)(nil),    // 11: vault.BucketDigestProto
	(*FetchItem)(nil),            // 12: vault.FetchItem
	(*FetchEntriesRequest)(nil),  // 13: vault.FetchEntriesRequest
	(*EntryBatch)(nil),           // 14: vault.EntryBatch
	(*DRHeartbeatRequest)(nil),   // 15: vault.DRHeartbeatRequest
	(*DRHeartbeatResponse)(nil),  // 16: vault.DRHeartbeatResponse
	(*SyncKeyringRequest)(nil),   // 17: vault.SyncKeyringRequest
	(*SyncKeyringResponse)(nil),  // 18: vault.SyncKeyringResponse
}
var file_vault_dr_replication_service_proto_depIdxs = []int32{
	5,  // 0: vault.CheckpointResponse.top_ranges:type_name -> vault.RangeDigest
	4,  // 1: vault.RangeDigest.span:type_name -> vault.RangeSpan
	4,  // 2: vault.RangeDigestRequest.spans:type_name -> vault.RangeSpan
	5,  // 3: vault.RangeDigestResponse.ranges:type_name -> vault.RangeDigest
	4,  // 4: vault.IBLTMessage.span:type_name -> vault.RangeSpan
	4,  // 5: vault.PrefixDigestRequest.span:type_name -> vault.RangeSpan
	11, // 6: vault.PrefixDigestResponse.buckets:type_name -> vault.BucketDigestProto
	4,  // 7: vault.FetchEntriesRequest.ranges:type_name -> vault.RangeSpan
	12, // 8: vault.FetchEntriesRequest.items:type_name -> vault.FetchItem
	0,  // 9: vault.EntryBatch.entries:type_name -> vault.EntryChange
	1,  // 10: vault.DRReplication.StreamChanges:input_type -> vault.StreamChangesRequest
	2,  // 11: vault.DRReplication.RequestCheckpoint:input_type -> vault.CheckpointRequest
	8,  // 12: vault.DRReplication.ExchangeIBLT:input_type -> vault.IBLTMessage
	6,  // 13: vault.DRReplication.ExchangeRangeDigests:input_type -> vault.RangeDigestRequest
	9,  // 14: vault.DRReplication.ExchangePrefixDigests:input_type -> vault.PrefixDigestRequest
	13, // 15: vault.DRReplication.FetchEntries:input_type -> vault.FetchEntriesRequest
	15, // 16: vault.DRReplication.Heartbeat:input_type -> vault.DRHeartbeatRequest
	17, // 17: vault.DRReplication.SyncKeyring:input_type -> vault.SyncKeyringRequest
	0,  // 18: vault.DRReplication.StreamChanges:output_type -> vault.EntryChange
	3,  // 19: vault.DRReplication.RequestCheckpoint:output_type -> vault.CheckpointResponse
	8,  // 20: vault.DRReplication.ExchangeIBLT:output_type -> vault.IBLTMessage
	7,  // 21: vault.DRReplication.ExchangeRangeDigests:output_type -> vault.RangeDigestResponse
	10, // 22: vault.DRReplication.ExchangePrefixDigests:output_type -> vault.PrefixDigestResponse
	14, // 23: vault.DRReplication.FetchEntries:output_type -> vault.EntryBatch
	16, // 24: vault.DRReplication.Heartbeat:output_type -> vault.DRHeartbeatResponse
	18, // 25: vault.DRReplication.SyncKeyring:output_type -> vault.SyncKeyringResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_vault_dr_replication_service_proto_init() }
func file_vault_dr_replication_service_proto_init() {
	if File_vault_dr_replication_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_dr_replication_service_proto_rawDesc), len(file_vault_dr_replication_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_dr_replication_service_proto_goTypes,
		DependencyIndexes: file_vault_dr_replication_service_proto_depIdxs,
		MessageInfos:      file_vault_dr_replication_service_proto_msgTypes,
	}.Build()
	File_vault_dr_replication_service_proto = out.File
	file_vault_dr_replication_service_proto_goTypes = nil
	file_vault_dr_replication_service_proto_depIdxs = nil
}
