// Copyright (c) OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: vault/dr_replication_service.proto

package vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryChange represents a single storage mutation.
type EntryChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// op_type: "put" or "delete"
	OpType string `protobuf:"bytes,1,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	// key is the storage path.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// value is the (encrypted) entry bytes. Empty for deletes.
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// seal_wrap indicates if the entry uses seal wrapping.
	SealWrap bool `protobuf:"varint,4,opt,name=seal_wrap,json=sealWrap,proto3" json:"seal_wrap,omitempty"`
	// raft_index is the primary's Raft log index for this mutation.
	RaftIndex uint64 `protobuf:"varint,5,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	// kid is the Key IDentifier (HMAC of the storage key). Used in
	// FetchEntries delete responses where the primary cannot resolve
	// the key (it was deleted). The secondary uses its local KID->key
	// map to resolve the actual storage path.
	Kid           []byte `protobuf:"bytes,6,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryChange) Reset() {
	*x = EntryChange{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryChange) ProtoMessage() {}

func (x *EntryChange) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryChange.ProtoReflect.Descriptor instead.
func (*EntryChange) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{0}
}

func (x *EntryChange) GetOpType() string {
	if x != nil {
		return x.OpType
	}
	return ""
}

func (x *EntryChange) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EntryChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EntryChange) GetSealWrap() bool {
	if x != nil {
		return x.SealWrap
	}
	return false
}

func (x *EntryChange) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

func (x *EntryChange) GetKid() []byte {
	if x != nil {
		return x.Kid
	}
	return nil
}

// StreamChangesUpstream is the client-to-server message envelope for the
// bidirectional StreamChanges RPC. The first message must be an init
// carrying the StreamChangesRequest. Subsequent messages carry WindowUpdate
// credits to replenish the primary's per-subscriber send budget.
type StreamChangesUpstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*StreamChangesUpstream_Init
	//	*StreamChangesUpstream_WindowUpdate
	Msg           isStreamChangesUpstream_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChangesUpstream) Reset() {
	*x = StreamChangesUpstream{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChangesUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChangesUpstream) ProtoMessage() {}

func (x *StreamChangesUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChangesUpstream.ProtoReflect.Descriptor instead.
func (*StreamChangesUpstream) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{1}
}

func (x *StreamChangesUpstream) GetMsg() isStreamChangesUpstream_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *StreamChangesUpstream) GetInit() *StreamChangesRequest {
	if x != nil {
		if x, ok := x.Msg.(*StreamChangesUpstream_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *StreamChangesUpstream) GetWindowUpdate() *WindowUpdate {
	if x != nil {
		if x, ok := x.Msg.(*StreamChangesUpstream_WindowUpdate); ok {
			return x.WindowUpdate
		}
	}
	return nil
}

type isStreamChangesUpstream_Msg interface {
	isStreamChangesUpstream_Msg()
}

type StreamChangesUpstream_Init struct {
	Init *StreamChangesRequest `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type StreamChangesUpstream_WindowUpdate struct {
	WindowUpdate *WindowUpdate `protobuf:"bytes,2,opt,name=window_update,json=windowUpdate,proto3,oneof"`
}

func (*StreamChangesUpstream_Init) isStreamChangesUpstream_Msg() {}

func (*StreamChangesUpstream_WindowUpdate) isStreamChangesUpstream_Msg() {}

// WindowUpdate carries credit replenishment from the secondary to the
// primary. The secondary sends this after flushing a batch of entries,
// allowing the primary to resume sending.
type WindowUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// credits is the number of additional entries the secondary is ready
	// to accept.
	Credits       uint64 `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowUpdate) Reset() {
	*x = WindowUpdate{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowUpdate) ProtoMessage() {}

func (x *WindowUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowUpdate.ProtoReflect.Descriptor instead.
func (*WindowUpdate) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{2}
}

func (x *WindowUpdate) GetCredits() uint64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

// StreamChangesRequest initiates the change stream from primary.
type StreamChangesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relationship_id identifies the DR relationship.
	RelationshipId string `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	// last_applied_index is the secondary's last known primary index.
	// Used as a hint for the primary to skip already-applied entries.
	LastAppliedIndex uint64 `protobuf:"varint,2,opt,name=last_applied_index,json=lastAppliedIndex,proto3" json:"last_applied_index,omitempty"`
	// initial_window is the number of entries the secondary is initially
	// willing to accept before requiring WindowUpdate replenishment.
	// If zero, the primary uses a default (drDefaultInitialWindow).
	InitialWindow uint64 `protobuf:"varint,3,opt,name=initial_window,json=initialWindow,proto3" json:"initial_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChangesRequest) Reset() {
	*x = StreamChangesRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChangesRequest) ProtoMessage() {}

func (x *StreamChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamChangesRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{3}
}

func (x *StreamChangesRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *StreamChangesRequest) GetLastAppliedIndex() uint64 {
	if x != nil {
		return x.LastAppliedIndex
	}
	return 0
}

func (x *StreamChangesRequest) GetInitialWindow() uint64 {
	if x != nil {
		return x.InitialWindow
	}
	return 0
}

// CheckpointRequest asks the primary to create a reconciliation checkpoint.
type CheckpointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckpointRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

// CheckpointResponse contains the checkpoint details.
type CheckpointResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// checkpoint_id is a unique identifier for this checkpoint.
	CheckpointId string `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// commit_index is the primary's Raft commit index at checkpoint time.
	CommitIndex uint64 `protobuf:"varint,2,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	// range_plan_version identifies the deterministic range planner
	// algorithm used to generate top_ranges.
	RangePlanVersion uint32 `protobuf:"varint,4,opt,name=range_plan_version,json=rangePlanVersion,proto3" json:"range_plan_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckpointResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CheckpointResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *CheckpointResponse) GetRangePlanVersion() uint32 {
	if x != nil {
		return x.RangePlanVersion
	}
	return 0
}

// RangeSpan is an inclusive KID interval.
type RangeSpan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start_kid and end_kid are inclusive 32-byte KID boundaries.
	StartKid []byte `protobuf:"bytes,1,opt,name=start_kid,json=startKid,proto3" json:"start_kid,omitempty"`
	EndKid   []byte `protobuf:"bytes,2,opt,name=end_kid,json=endKid,proto3" json:"end_kid,omitempty"`
	// split_depth indicates adaptive split depth from the parent range.
	SplitDepth    uint32 `protobuf:"varint,3,opt,name=split_depth,json=splitDepth,proto3" json:"split_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeSpan) Reset() {
	*x = RangeSpan{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSpan) ProtoMessage() {}

func (x *RangeSpan) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSpan.ProtoReflect.Descriptor instead.
func (*RangeSpan) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{6}
}

func (x *RangeSpan) GetStartKid() []byte {
	if x != nil {
		return x.StartKid
	}
	return nil
}

func (x *RangeSpan) GetEndKid() []byte {
	if x != nil {
		return x.EndKid
	}
	return nil
}

func (x *RangeSpan) GetSplitDepth() uint32 {
	if x != nil {
		return x.SplitDepth
	}
	return 0
}

// DirtyBitmapMessage carries the dirty range bitmap.
type DirtyBitmapMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId  string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	CheckpointId    string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	CheckpointIndex uint64                 `protobuf:"varint,3,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	StartIndex      uint64                 `protobuf:"varint,4,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"` // The Raft index since when changes are tracked
	Bitmap          []byte                 `protobuf:"bytes,5,opt,name=bitmap,proto3" json:"bitmap,omitempty"`                            // The bitmap itself
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DirtyBitmapMessage) Reset() {
	*x = DirtyBitmapMessage{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirtyBitmapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirtyBitmapMessage) ProtoMessage() {}

func (x *DirtyBitmapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirtyBitmapMessage.ProtoReflect.Descriptor instead.
func (*DirtyBitmapMessage) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{7}
}

func (x *DirtyBitmapMessage) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *DirtyBitmapMessage) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *DirtyBitmapMessage) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *DirtyBitmapMessage) GetStartIndex() uint64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *DirtyBitmapMessage) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

// RangeChecksum represents a simple checksum for a range.
type RangeChecksum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeId       uint64                 `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	Checksum      uint64                 `protobuf:"varint,2,opt,name=checksum,proto3" json:"checksum,omitempty"` // Simple XOR or CRC64
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeChecksum) Reset() {
	*x = RangeChecksum{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeChecksum) ProtoMessage() {}

func (x *RangeChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeChecksum.ProtoReflect.Descriptor instead.
func (*RangeChecksum) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{8}
}

func (x *RangeChecksum) GetRangeId() uint64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *RangeChecksum) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *RangeChecksum) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// RangeChecksumRequest requests checksums for specific ranges.
type RangeChecksumRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId    string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	CheckpointIndex uint64                 `protobuf:"varint,2,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	RangeIds        []uint64               `protobuf:"varint,3,rep,packed,name=range_ids,json=rangeIds,proto3" json:"range_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RangeChecksumRequest) Reset() {
	*x = RangeChecksumRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeChecksumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeChecksumRequest) ProtoMessage() {}

func (x *RangeChecksumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeChecksumRequest.ProtoReflect.Descriptor instead.
func (*RangeChecksumRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{9}
}

func (x *RangeChecksumRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *RangeChecksumRequest) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *RangeChecksumRequest) GetRangeIds() []uint64 {
	if x != nil {
		return x.RangeIds
	}
	return nil
}

// RangeChecksumResponse returns the requested range checksums.
type RangeChecksumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksums     []*RangeChecksum       `protobuf:"bytes,1,rep,name=checksums,proto3" json:"checksums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeChecksumResponse) Reset() {
	*x = RangeChecksumResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeChecksumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeChecksumResponse) ProtoMessage() {}

func (x *RangeChecksumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeChecksumResponse.ProtoReflect.Descriptor instead.
func (*RangeChecksumResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{10}
}

func (x *RangeChecksumResponse) GetChecksums() []*RangeChecksum {
	if x != nil {
		return x.Checksums
	}
	return nil
}

// RangeDigest is a fine-grained sub-range digest for drill-down.
type RangeDigest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Span             *RangeSpan             `protobuf:"bytes,1,opt,name=span,proto3" json:"span,omitempty"`
	Count            uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XorKeyHash       []byte                 `protobuf:"bytes,3,opt,name=xor_key_hash,json=xorKeyHash,proto3" json:"xor_key_hash,omitempty"`       // 32-byte XOR of SHA256(KID) values
	XorValueHash     []byte                 `protobuf:"bytes,4,opt,name=xor_value_hash,json=xorValueHash,proto3" json:"xor_value_hash,omitempty"` // 32-byte XOR of SHA256(KID||VID) values
	ApproxValueBytes uint64                 `protobuf:"varint,5,opt,name=approx_value_bytes,json=approxValueBytes,proto3" json:"approx_value_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RangeDigest) Reset() {
	*x = RangeDigest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDigest) ProtoMessage() {}

func (x *RangeDigest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDigest.ProtoReflect.Descriptor instead.
func (*RangeDigest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{11}
}

func (x *RangeDigest) GetSpan() *RangeSpan {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *RangeDigest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RangeDigest) GetXorKeyHash() []byte {
	if x != nil {
		return x.XorKeyHash
	}
	return nil
}

func (x *RangeDigest) GetXorValueHash() []byte {
	if x != nil {
		return x.XorValueHash
	}
	return nil
}

func (x *RangeDigest) GetApproxValueBytes() uint64 {
	if x != nil {
		return x.ApproxValueBytes
	}
	return 0
}

// RangeDigestRequest asks the primary for fine-grained sub-range digests.
type RangeDigestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId    string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	CheckpointIndex uint64                 `protobuf:"varint,2,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	// parent_span is the mismatched range to drill into.
	ParentSpan    *RangeSpan `protobuf:"bytes,3,opt,name=parent_span,json=parentSpan,proto3" json:"parent_span,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeDigestRequest) Reset() {
	*x = RangeDigestRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDigestRequest) ProtoMessage() {}

func (x *RangeDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDigestRequest.ProtoReflect.Descriptor instead.
func (*RangeDigestRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{12}
}

func (x *RangeDigestRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *RangeDigestRequest) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *RangeDigestRequest) GetParentSpan() *RangeSpan {
	if x != nil {
		return x.ParentSpan
	}
	return nil
}

// RangeDigestResponse returns the sub-range digests for a drilled-down range.
type RangeDigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       []*RangeDigest         `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeDigestResponse) Reset() {
	*x = RangeDigestResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeDigestResponse) ProtoMessage() {}

func (x *RangeDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeDigestResponse.ProtoReflect.Descriptor instead.
func (*RangeDigestResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{13}
}

func (x *RangeDigestResponse) GetDigests() []*RangeDigest {
	if x != nil {
		return x.Digests
	}
	return nil
}

// FetchEntriesRequest asks the primary for specific entries by KID.
type FetchItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid identifies the item to fetch.
	Kid []byte `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// expected_vid is the VID derived on the secondary from the active
	// checkpoint diff. The primary must verify fetched value provenance.
	ExpectedVid   []byte `protobuf:"bytes,2,opt,name=expected_vid,json=expectedVid,proto3" json:"expected_vid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchItem) Reset() {
	*x = FetchItem{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchItem) ProtoMessage() {}

func (x *FetchItem) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchItem.ProtoReflect.Descriptor instead.
func (*FetchItem) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{14}
}

func (x *FetchItem) GetKid() []byte {
	if x != nil {
		return x.Kid
	}
	return nil
}

func (x *FetchItem) GetExpectedVid() []byte {
	if x != nil {
		return x.ExpectedVid
	}
	return nil
}

// FetchEntriesRequest asks the primary for specific entries by KID.
type FetchEntriesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// kids is the list of KID hashes to fetch entries for.
	Kids [][]byte `protobuf:"bytes,2,rep,name=kids,proto3" json:"kids,omitempty"`
	// include_deletes indicates whether tombstoned/deleted entries
	// should be included in the response.
	IncludeDeletes bool `protobuf:"varint,3,opt,name=include_deletes,json=includeDeletes,proto3" json:"include_deletes,omitempty"`
	// bucket_prefix_length and bucket_indices enable bucket-based
	// fetching for prefix digest reconciliation. When set, the primary
	// returns all entries whose KID falls into the specified buckets,
	// not just the KIDs listed in the kids field.
	BucketPrefixLength uint32   `protobuf:"varint,4,opt,name=bucket_prefix_length,json=bucketPrefixLength,proto3" json:"bucket_prefix_length,omitempty"`
	BucketIndices      []uint32 `protobuf:"varint,5,rep,packed,name=bucket_indices,json=bucketIndices,proto3" json:"bucket_indices,omitempty"`
	// ranges optionally requests all entries in the provided KID intervals.
	Ranges []*RangeSpan `protobuf:"bytes,6,rep,name=ranges,proto3" json:"ranges,omitempty"`
	// checkpoint_index fences this request to a specific checkpoint tuple.
	CheckpointIndex uint64 `protobuf:"varint,7,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	// items is a provenance-safe fetch list of (KID, expected_VID) pairs.
	// When checkpoint_index is set and point fetches are requested, items
	// should be used instead of kids.
	Items         []*FetchItem `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchEntriesRequest) Reset() {
	*x = FetchEntriesRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEntriesRequest) ProtoMessage() {}

func (x *FetchEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEntriesRequest.ProtoReflect.Descriptor instead.
func (*FetchEntriesRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{15}
}

func (x *FetchEntriesRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *FetchEntriesRequest) GetKids() [][]byte {
	if x != nil {
		return x.Kids
	}
	return nil
}

func (x *FetchEntriesRequest) GetIncludeDeletes() bool {
	if x != nil {
		return x.IncludeDeletes
	}
	return false
}

func (x *FetchEntriesRequest) GetBucketPrefixLength() uint32 {
	if x != nil {
		return x.BucketPrefixLength
	}
	return 0
}

func (x *FetchEntriesRequest) GetBucketIndices() []uint32 {
	if x != nil {
		return x.BucketIndices
	}
	return nil
}

func (x *FetchEntriesRequest) GetRanges() []*RangeSpan {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *FetchEntriesRequest) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

func (x *FetchEntriesRequest) GetItems() []*FetchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// EntryBatch is a batch of storage entries.
type EntryBatch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*EntryChange         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// errors lists KIDs that could not be fetched due to storage
	// errors. The secondary should retry these in a subsequent
	// reconciliation pass.
	FailedKids [][]byte `protobuf:"bytes,2,rep,name=failed_kids,json=failedKids,proto3" json:"failed_kids,omitempty"`
	// checkpoint tuple provenance for this batch.
	CheckpointId    string `protobuf:"bytes,3,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	CheckpointIndex uint64 `protobuf:"varint,4,opt,name=checkpoint_index,json=checkpointIndex,proto3" json:"checkpoint_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EntryBatch) Reset() {
	*x = EntryBatch{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryBatch) ProtoMessage() {}

func (x *EntryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryBatch.ProtoReflect.Descriptor instead.
func (*EntryBatch) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{16}
}

func (x *EntryBatch) GetEntries() []*EntryChange {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *EntryBatch) GetFailedKids() [][]byte {
	if x != nil {
		return x.FailedKids
	}
	return nil
}

func (x *EntryBatch) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *EntryBatch) GetCheckpointIndex() uint64 {
	if x != nil {
		return x.CheckpointIndex
	}
	return 0
}

// DRHeartbeatRequest is sent periodically from secondary to primary.
type DRHeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	AppliedIndex   uint64                 `protobuf:"varint,2,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	Term           uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	NodeId         string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DRHeartbeatRequest) Reset() {
	*x = DRHeartbeatRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRHeartbeatRequest) ProtoMessage() {}

func (x *DRHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*DRHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{17}
}

func (x *DRHeartbeatRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *DRHeartbeatRequest) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *DRHeartbeatRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *DRHeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// DRHeartbeatResponse is the primary's reply to a heartbeat.
type DRHeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrimaryIndex     uint64                 `protobuf:"varint,1,opt,name=primary_index,json=primaryIndex,proto3" json:"primary_index,omitempty"`
	PrimaryTerm      uint64                 `protobuf:"varint,2,opt,name=primary_term,json=primaryTerm,proto3" json:"primary_term,omitempty"`
	ReplicationState uint32                 `protobuf:"varint,3,opt,name=replication_state,json=replicationState,proto3" json:"replication_state,omitempty"`
	// leader_cluster_addr is the active primary's cluster gRPC address.
	// Populated on every heartbeat so the secondary always knows where
	// the current leader is, enabling fast reconnection after stepdowns
	// without requiring a load balancer.
	LeaderClusterAddr string `protobuf:"bytes,4,opt,name=leader_cluster_addr,json=leaderClusterAddr,proto3" json:"leader_cluster_addr,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DRHeartbeatResponse) Reset() {
	*x = DRHeartbeatResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRHeartbeatResponse) ProtoMessage() {}

func (x *DRHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*DRHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{18}
}

func (x *DRHeartbeatResponse) GetPrimaryIndex() uint64 {
	if x != nil {
		return x.PrimaryIndex
	}
	return 0
}

func (x *DRHeartbeatResponse) GetPrimaryTerm() uint64 {
	if x != nil {
		return x.PrimaryTerm
	}
	return 0
}

func (x *DRHeartbeatResponse) GetReplicationState() uint32 {
	if x != nil {
		return x.ReplicationState
	}
	return 0
}

func (x *DRHeartbeatResponse) GetLeaderClusterAddr() string {
	if x != nil {
		return x.LeaderClusterAddr
	}
	return ""
}

// DRRedirectDetail is attached as a gRPC status detail when a standby
// node receives a DR replication RPC that must be handled by the active
// leader. The secondary should reconnect to the address in
// leader_cluster_addr.
type DRRedirectDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeaderClusterAddr string                 `protobuf:"bytes,1,opt,name=leader_cluster_addr,json=leaderClusterAddr,proto3" json:"leader_cluster_addr,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DRRedirectDetail) Reset() {
	*x = DRRedirectDetail{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRRedirectDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRRedirectDetail) ProtoMessage() {}

func (x *DRRedirectDetail) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRRedirectDetail.ProtoReflect.Descriptor instead.
func (*DRRedirectDetail) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{19}
}

func (x *DRRedirectDetail) GetLeaderClusterAddr() string {
	if x != nil {
		return x.LeaderClusterAddr
	}
	return ""
}

// SyncKeyringRequest is sent by the secondary during bootstrap to
// request the primary's keyring.
type SyncKeyringRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId        string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	ClientEphemeralPubkey []byte                 `protobuf:"bytes,2,opt,name=client_ephemeral_pubkey,json=clientEphemeralPubkey,proto3" json:"client_ephemeral_pubkey,omitempty"`
	ClientNonce           []byte                 `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncKeyringRequest) Reset() {
	*x = SyncKeyringRequest{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeyringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeyringRequest) ProtoMessage() {}

func (x *SyncKeyringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeyringRequest.ProtoReflect.Descriptor instead.
func (*SyncKeyringRequest) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{20}
}

func (x *SyncKeyringRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *SyncKeyringRequest) GetClientEphemeralPubkey() []byte {
	if x != nil {
		return x.ClientEphemeralPubkey
	}
	return nil
}

func (x *SyncKeyringRequest) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

// SyncKeyringResponse carries the encrypted keyring, root key entry,
// and the root key wrapped to the secondary's ephemeral public key.
type SyncKeyringResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keyring_entry is the raw value of "core/keyring" from physical storage.
	KeyringEntry []byte `protobuf:"bytes,1,opt,name=keyring_entry,json=keyringEntry,proto3" json:"keyring_entry,omitempty"`
	// root_key_entry is the raw value of "core/root-key" from physical storage.
	RootKeyEntry []byte `protobuf:"bytes,2,opt,name=root_key_entry,json=rootKeyEntry,proto3" json:"root_key_entry,omitempty"`
	// wrapped_root_key is the root key encrypted with a symmetric key
	// derived from ECDH(primary_ephemeral, secondary_ephemeral_pubkey).
	WrappedRootKey []byte `protobuf:"bytes,3,opt,name=wrapped_root_key,json=wrappedRootKey,proto3" json:"wrapped_root_key,omitempty"`
	// server_ephemeral_pubkey is the primary's ephemeral public key used
	// for ECDH key agreement.
	ServerEphemeralPubkey []byte `protobuf:"bytes,4,opt,name=server_ephemeral_pubkey,json=serverEphemeralPubkey,proto3" json:"server_ephemeral_pubkey,omitempty"`
	// wrap_nonce is the AEAD nonce used to encrypt wrapped_root_key.
	WrapNonce []byte `protobuf:"bytes,5,opt,name=wrap_nonce,json=wrapNonce,proto3" json:"wrap_nonce,omitempty"`
	// wrap_aad_version is the protocol version encoded in AEAD AAD.
	WrapAadVersion uint32 `protobuf:"varint,6,opt,name=wrap_aad_version,json=wrapAadVersion,proto3" json:"wrap_aad_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncKeyringResponse) Reset() {
	*x = SyncKeyringResponse{}
	mi := &file_vault_dr_replication_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncKeyringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncKeyringResponse) ProtoMessage() {}

func (x *SyncKeyringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_dr_replication_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncKeyringResponse.ProtoReflect.Descriptor instead.
func (*SyncKeyringResponse) Descriptor() ([]byte, []int) {
	return file_vault_dr_replication_service_proto_rawDescGZIP(), []int{21}
}

func (x *SyncKeyringResponse) GetKeyringEntry() []byte {
	if x != nil {
		return x.KeyringEntry
	}
	return nil
}

func (x *SyncKeyringResponse) GetRootKeyEntry() []byte {
	if x != nil {
		return x.RootKeyEntry
	}
	return nil
}

func (x *SyncKeyringResponse) GetWrappedRootKey() []byte {
	if x != nil {
		return x.WrappedRootKey
	}
	return nil
}

func (x *SyncKeyringResponse) GetServerEphemeralPubkey() []byte {
	if x != nil {
		return x.ServerEphemeralPubkey
	}
	return nil
}

func (x *SyncKeyringResponse) GetWrapNonce() []byte {
	if x != nil {
		return x.WrapNonce
	}
	return nil
}

func (x *SyncKeyringResponse) GetWrapAadVersion() uint32 {
	if x != nil {
		return x.WrapAadVersion
	}
	return 0
}

var File_vault_dr_replication_service_proto protoreflect.FileDescriptor

const file_vault_dr_replication_service_proto_rawDesc = "" +
	"\n" +
	"\"vault/dr_replication_service.proto\x12\x05vault\"\x9c\x01\n" +
	"\vEntryChange\x12\x17\n" +
	"\aop_type\x18\x01 \x01(\tR\x06opType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\tseal_wrap\x18\x04 \x01(\bR\bsealWrap\x12\x1d\n" +
	"\n" +
	"raft_index\x18\x05 \x01(\x04R\traftIndex\x12\x10\n" +
	"\x03kid\x18\x06 \x01(\fR\x03kid\"\x8d\x01\n" +
	"\x15StreamChangesUpstream\x121\n" +
	"\x04init\x18\x01 \x01(\v2\x1b.vault.StreamChangesRequestH\x00R\x04init\x12:\n" +
	"\rwindow_update\x18\x02 \x01(\v2\x13.vault.WindowUpdateH\x00R\fwindowUpdateB\x05\n" +
	"\x03msg\"(\n" +
	"\fWindowUpdate\x12\x18\n" +
	"\acredits\x18\x01 \x01(\x04R\acredits\"\x94\x01\n" +
	"\x14StreamChangesRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x12,\n" +
	"\x12last_applied_index\x18\x02 \x01(\x04R\x10lastAppliedIndex\x12%\n" +
	"\x0einitial_window\x18\x03 \x01(\x04R\rinitialWindow\"<\n" +
	"\x11CheckpointRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\"\x8a\x01\n" +
	"\x12CheckpointResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12!\n" +
	"\fcommit_index\x18\x02 \x01(\x04R\vcommitIndex\x12,\n" +
	"\x12range_plan_version\x18\x04 \x01(\rR\x10rangePlanVersion\"b\n" +
	"\tRangeSpan\x12\x1b\n" +
	"\tstart_kid\x18\x01 \x01(\fR\bstartKid\x12\x17\n" +
	"\aend_kid\x18\x02 \x01(\fR\x06endKid\x12\x1f\n" +
	"\vsplit_depth\x18\x03 \x01(\rR\n" +
	"splitDepth\"\xc6\x01\n" +
	"\x12DirtyBitmapMessage\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12)\n" +
	"\x10checkpoint_index\x18\x03 \x01(\x04R\x0fcheckpointIndex\x12\x1f\n" +
	"\vstart_index\x18\x04 \x01(\x04R\n" +
	"startIndex\x12\x16\n" +
	"\x06bitmap\x18\x05 \x01(\fR\x06bitmap\"\\\n" +
	"\rRangeChecksum\x12\x19\n" +
	"\brange_id\x18\x01 \x01(\x04R\arangeId\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\x04R\bchecksum\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"\x83\x01\n" +
	"\x14RangeChecksumRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12)\n" +
	"\x10checkpoint_index\x18\x02 \x01(\x04R\x0fcheckpointIndex\x12\x1b\n" +
	"\trange_ids\x18\x03 \x03(\x04R\brangeIds\"K\n" +
	"\x15RangeChecksumResponse\x122\n" +
	"\tchecksums\x18\x01 \x03(\v2\x14.vault.RangeChecksumR\tchecksums\"\xbf\x01\n" +
	"\vRangeDigest\x12$\n" +
	"\x04span\x18\x01 \x01(\v2\x10.vault.RangeSpanR\x04span\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12 \n" +
	"\fxor_key_hash\x18\x03 \x01(\fR\n" +
	"xorKeyHash\x12$\n" +
	"\x0exor_value_hash\x18\x04 \x01(\fR\fxorValueHash\x12,\n" +
	"\x12approx_value_bytes\x18\x05 \x01(\x04R\x10approxValueBytes\"\x97\x01\n" +
	"\x12RangeDigestRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12)\n" +
	"\x10checkpoint_index\x18\x02 \x01(\x04R\x0fcheckpointIndex\x121\n" +
	"\vparent_span\x18\x03 \x01(\v2\x10.vault.RangeSpanR\n" +
	"parentSpan\"C\n" +
	"\x13RangeDigestResponse\x12,\n" +
	"\adigests\x18\x01 \x03(\v2\x12.vault.RangeDigestR\adigests\"@\n" +
	"\tFetchItem\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\fR\x03kid\x12!\n" +
	"\fexpected_vid\x18\x02 \x01(\fR\vexpectedVid\"\xcd\x02\n" +
	"\x13FetchEntriesRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x12\n" +
	"\x04kids\x18\x02 \x03(\fR\x04kids\x12'\n" +
	"\x0finclude_deletes\x18\x03 \x01(\bR\x0eincludeDeletes\x120\n" +
	"\x14bucket_prefix_length\x18\x04 \x01(\rR\x12bucketPrefixLength\x12%\n" +
	"\x0ebucket_indices\x18\x05 \x03(\rR\rbucketIndices\x12(\n" +
	"\x06ranges\x18\x06 \x03(\v2\x10.vault.RangeSpanR\x06ranges\x12)\n" +
	"\x10checkpoint_index\x18\a \x01(\x04R\x0fcheckpointIndex\x12&\n" +
	"\x05items\x18\b \x03(\v2\x10.vault.FetchItemR\x05items\"\xab\x01\n" +
	"\n" +
	"EntryBatch\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.vault.EntryChangeR\aentries\x12\x1f\n" +
	"\vfailed_kids\x18\x02 \x03(\fR\n" +
	"failedKids\x12#\n" +
	"\rcheckpoint_id\x18\x03 \x01(\tR\fcheckpointId\x12)\n" +
	"\x10checkpoint_index\x18\x04 \x01(\x04R\x0fcheckpointIndex\"\x8f\x01\n" +
	"\x12DRHeartbeatRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x12#\n" +
	"\rapplied_index\x18\x02 \x01(\x04R\fappliedIndex\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"\xba\x01\n" +
	"\x13DRHeartbeatResponse\x12#\n" +
	"\rprimary_index\x18\x01 \x01(\x04R\fprimaryIndex\x12!\n" +
	"\fprimary_term\x18\x02 \x01(\x04R\vprimaryTerm\x12+\n" +
	"\x11replication_state\x18\x03 \x01(\rR\x10replicationState\x12.\n" +
	"\x13leader_cluster_addr\x18\x04 \x01(\tR\x11leaderClusterAddr\"B\n" +
	"\x10DRRedirectDetail\x12.\n" +
	"\x13leader_cluster_addr\x18\x01 \x01(\tR\x11leaderClusterAddr\"\x98\x01\n" +
	"\x12SyncKeyringRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x126\n" +
	"\x17client_ephemeral_pubkey\x18\x02 \x01(\fR\x15clientEphemeralPubkey\x12!\n" +
	"\fclient_nonce\x18\x03 \x01(\fR\vclientNonce\"\x8b\x02\n" +
	"\x13SyncKeyringResponse\x12#\n" +
	"\rkeyring_entry\x18\x01 \x01(\fR\fkeyringEntry\x12$\n" +
	"\x0eroot_key_entry\x18\x02 \x01(\fR\frootKeyEntry\x12(\n" +
	"\x10wrapped_root_key\x18\x03 \x01(\fR\x0ewrappedRootKey\x126\n" +
	"\x17server_ephemeral_pubkey\x18\x04 \x01(\fR\x15serverEphemeralPubkey\x12\x1d\n" +
	"\n" +
	"wrap_nonce\x18\x05 \x01(\fR\twrapNonce\x12(\n" +
	"\x10wrap_aad_version\x18\x06 \x01(\rR\x0ewrapAadVersion2\xeb\x04\n" +
	"\rDRReplication\x12F\n" +
	"\rStreamChanges\x12\x1c.vault.StreamChangesUpstream\x1a\x11.vault.EntryBatch\"\x00(\x010\x01\x12J\n" +
	"\x11RequestCheckpoint\x12\x18.vault.CheckpointRequest\x1a\x19.vault.CheckpointResponse\"\x00\x12M\n" +
	"\x13ExchangeDirtyBitmap\x12\x19.vault.DirtyBitmapMessage\x1a\x19.vault.DirtyBitmapMessage\"\x00\x12U\n" +
	"\x16ExchangeRangeChecksums\x12\x1b.vault.RangeChecksumRequest\x1a\x1c.vault.RangeChecksumResponse\"\x00\x12O\n" +
	"\x14ExchangeRangeDigests\x12\x19.vault.RangeDigestRequest\x1a\x1a.vault.RangeDigestResponse\"\x00\x12A\n" +
	"\fFetchEntries\x12\x1a.vault.FetchEntriesRequest\x1a\x11.vault.EntryBatch\"\x000\x01\x12D\n" +
	"\tHeartbeat\x12\x19.vault.DRHeartbeatRequest\x1a\x1a.vault.DRHeartbeatResponse\"\x00\x12F\n" +
	"\vSyncKeyring\x12\x19.vault.SyncKeyringRequest\x1a\x1a.vault.SyncKeyringResponse\"\x00B\"Z github.com/openbao/openbao/vaultb\x06proto3"

var (
	file_vault_dr_replication_service_proto_rawDescOnce sync.Once
	file_vault_dr_replication_service_proto_rawDescData []byte
)

func file_vault_dr_replication_service_proto_rawDescGZIP() []byte {
	file_vault_dr_replication_service_proto_rawDescOnce.Do(func() {
		file_vault_dr_replication_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_dr_replication_service_proto_rawDesc), len(file_vault_dr_replication_service_proto_rawDesc)))
	})
	return file_vault_dr_replication_service_proto_rawDescData
}

var file_vault_dr_replication_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_vault_dr_replication_service_proto_goTypes = []any{
	(*EntryChange)(nil),           // 0: vault.EntryChange
	(*StreamChangesUpstream)(nil), // 1: vault.StreamChangesUpstream
	(*WindowUpdate)(nil),          // 2: vault.WindowUpdate
	(*StreamChangesRequest)(nil),  // 3: vault.StreamChangesRequest
	(*CheckpointRequest)(nil),     // 4: vault.CheckpointRequest
	(*CheckpointResponse)(nil),    // 5: vault.CheckpointResponse
	(*RangeSpan)(nil),             // 6: vault.RangeSpan
	(*DirtyBitmapMessage)(nil),    // 7: vault.DirtyBitmapMessage
	(*RangeChecksum)(nil),         // 8: vault.RangeChecksum
	(*RangeChecksumRequest)(nil),  // 9: vault.RangeChecksumRequest
	(*RangeChecksumResponse)(nil), // 10: vault.RangeChecksumResponse
	(*RangeDigest)(nil),           // 11: vault.RangeDigest
	(*RangeDigestRequest)(nil),    // 12: vault.RangeDigestRequest
	(*RangeDigestResponse)(nil),   // 13: vault.RangeDigestResponse
	(*FetchItem)(nil),             // 14: vault.FetchItem
	(*FetchEntriesRequest)(nil),   // 15: vault.FetchEntriesRequest
	(*EntryBatch)(nil),            // 16: vault.EntryBatch
	(*DRHeartbeatRequest)(nil),    // 17: vault.DRHeartbeatRequest
	(*DRHeartbeatResponse)(nil),   // 18: vault.DRHeartbeatResponse
	(*DRRedirectDetail)(nil),      // 19: vault.DRRedirectDetail
	(*SyncKeyringRequest)(nil),    // 20: vault.SyncKeyringRequest
	(*SyncKeyringResponse)(nil),   // 21: vault.SyncKeyringResponse
}
var file_vault_dr_replication_service_proto_depIdxs = []int32{
	3,  // 0: vault.StreamChangesUpstream.init:type_name -> vault.StreamChangesRequest
	2,  // 1: vault.StreamChangesUpstream.window_update:type_name -> vault.WindowUpdate
	8,  // 2: vault.RangeChecksumResponse.checksums:type_name -> vault.RangeChecksum
	6,  // 3: vault.RangeDigest.span:type_name -> vault.RangeSpan
	6,  // 4: vault.RangeDigestRequest.parent_span:type_name -> vault.RangeSpan
	11, // 5: vault.RangeDigestResponse.digests:type_name -> vault.RangeDigest
	6,  // 6: vault.FetchEntriesRequest.ranges:type_name -> vault.RangeSpan
	14, // 7: vault.FetchEntriesRequest.items:type_name -> vault.FetchItem
	0,  // 8: vault.EntryBatch.entries:type_name -> vault.EntryChange
	1,  // 9: vault.DRReplication.StreamChanges:input_type -> vault.StreamChangesUpstream
	4,  // 10: vault.DRReplication.RequestCheckpoint:input_type -> vault.CheckpointRequest
	7,  // 11: vault.DRReplication.ExchangeDirtyBitmap:input_type -> vault.DirtyBitmapMessage
	9,  // 12: vault.DRReplication.ExchangeRangeChecksums:input_type -> vault.RangeChecksumRequest
	12, // 13: vault.DRReplication.ExchangeRangeDigests:input_type -> vault.RangeDigestRequest
	15, // 14: vault.DRReplication.FetchEntries:input_type -> vault.FetchEntriesRequest
	17, // 15: vault.DRReplication.Heartbeat:input_type -> vault.DRHeartbeatRequest
	20, // 16: vault.DRReplication.SyncKeyring:input_type -> vault.SyncKeyringRequest
	16, // 17: vault.DRReplication.StreamChanges:output_type -> vault.EntryBatch
	5,  // 18: vault.DRReplication.RequestCheckpoint:output_type -> vault.CheckpointResponse
	7,  // 19: vault.DRReplication.ExchangeDirtyBitmap:output_type -> vault.DirtyBitmapMessage
	10, // 20: vault.DRReplication.ExchangeRangeChecksums:output_type -> vault.RangeChecksumResponse
	13, // 21: vault.DRReplication.ExchangeRangeDigests:output_type -> vault.RangeDigestResponse
	16, // 22: vault.DRReplication.FetchEntries:output_type -> vault.EntryBatch
	18, // 23: vault.DRReplication.Heartbeat:output_type -> vault.DRHeartbeatResponse
	21, // 24: vault.DRReplication.SyncKeyring:output_type -> vault.SyncKeyringResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_vault_dr_replication_service_proto_init() }
func file_vault_dr_replication_service_proto_init() {
	if File_vault_dr_replication_service_proto != nil {
		return
	}
	file_vault_dr_replication_service_proto_msgTypes[1].OneofWrappers = []any{
		(*StreamChangesUpstream_Init)(nil),
		(*StreamChangesUpstream_WindowUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_dr_replication_service_proto_rawDesc), len(file_vault_dr_replication_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_dr_replication_service_proto_goTypes,
		DependencyIndexes: file_vault_dr_replication_service_proto_depIdxs,
		MessageInfos:      file_vault_dr_replication_service_proto_msgTypes,
	}.Build()
	File_vault_dr_replication_service_proto = out.File
	file_vault_dr_replication_service_proto_goTypes = nil
	file_vault_dr_replication_service_proto_depIdxs = nil
}
